language: julia
os:
  - linux
  - osx
julia:
  - 1.1
notifications:
  email: true
script:
  - julia -e 'using Pkg; Pkg.add("Mimi")'
  - julia -e 'using Pkg; Pkg.add("CSVFiles")'
  - julia -e 'using Pkg; Pkg.add("CSV")'
  - julia -e 'using Pkg; Pkg.add("Query")'
  - julia -e 'using Pkg; Pkg.add("DataFrames")'
  - julia -e 'using Pkg; Pkg.add("Distributions")'
  - julia -e 'using Pkg; Pkg.add("Query")'
  - julia -e 'using Pkg; Pkg.add("Missings")'
  - julia -e 'using Pkg; Pkg.add("FileIO")'
  - julia -e 'using Pkg; Pkg.add("StatsBase")'
  - julia --code-coverage=user test/runtests_clean.jl
after_success:
  # push coverage results to Codecov
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
