name = "MimiPAGE2020"
uuid = "daa1807e-96ac-4669-bc57-6ed081383131"
version = "1.9.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CSVFiles = "5d742f6a-9f54-50ce-8119-2520741973ca"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Query = "1a8c2f83-1ff3-5112-b086-8aa67b057ba1"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
ExcelReaders = "c04bee98-12a5-510c-87df-2a230cb6e075"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Mimi = "e4e893b0-ee5e-52ea-8111-44b3bdec128c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CSVFiles = "0.16, 1"
DataFrames = "0.19.1, 0.20, 0.21, 0.22, 1.0"
Distributions = "0.20, 0.21, 0.22, 0.23, 0.24, 0.25"
ExcelReaders = "0.11"
Mimi = "1.3"
Query = "0.12, 1.0"
StatsBase = "0.32, 0.33"
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
